### PR TITLE
API: Add module exist check for endpoints

### LINKED ISSUE #213: API: module's callables endpoint returns 200 even if module doesn't exist
## Describe the bug
The endpoint that is meant to return the list of callables for a specific module in the package returns successful response (w/ empty set) even if module doesn't exist for the package.

## To Reproduce
**POST** `https://api.fasten-project.eu/api/mvn/packages/jboss:jbossmq-client/3.2.3/modules/callables`
With body: `abcde` (random string)

-> returns 200

## Expected behavior
The endpoint shall return `404` if module is not found for the package.

### PR DESCRIPTION
**Pull request by romatallinn**
Closes #213 

## Description
PR adds check for module existence in the endpoints of internal elements.  In the current implementation, if the module doesn't exist, such endpoints would still return `200` with an empty set, while supposed `404`.

For example, retrieval of the callables for a module, `/{pkg}/{pkg_ver}/modules/callables`.

### CODE REVIEW

**Comment by romatallinn** [comment]
I found out that there are quite a lot of endpoints that had the same issue. I hope I added the necessary checks for all of them. So if a wrong package or module will be requested by the user, API will not return just an empty set, but actually will throw an error.

But @MihhailSokolov I'd appreciate your opinion on whether or not my solution is optimal. In particular, `assertPackageExistence` and `assertModulesExistence` in `MetadataDao.java` are the methods that check for it. Do you know maybe there is a more elegant way to assert it within the main query? Or this solution will work?

**Comment by MihhailSokolov** [comment]
Sure, I will review it either later today or tomorrow. I would really appreciate it if you could also increase a timeout for all requests while we are at it. This should be as easy as setting some properties in the `application.properties` of the REST API. Thank you!

File: core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java [hunk 1]
```diff
@@ -1056,6 +1089,9 @@ public String getPackageModules(String packageName,
                                     String packageVersion,
                                     int offset,
                                     int limit) {
+
+        if(!assertPackageExistence(packageName, packageVersion)) return null;
```
Comment (MihhailSokolov) [inline core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java:1093]: This way we need to run 2 queries whenever the package or modules are retrieved. This might affect the performance (not in a good way). I think a better solution be to prepend the `count(<retrieved field>)` to select and just check if it is > 0 before returning the result and if <1 return `null`, i.e. in this case the query would be something like `select count(f.*), f.* from ....`.
Same applies to the other changed methods.

**Review by MihhailSokolov — APPROVED** [review]
See the comment. I think it is not the best solution to run 2 queries each time we want to retrieve packages or modules. The existence can be checked in the same query using `count(...)` statement. I would also appreciate if you could increase the timeout for the REST API.
Thank you!

File: core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java (hunk 1 above)
Comment (romatallinn) [reply core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java:1093]: > a better solution be to prepend the `count(<retrieved field>)`
I surely thought about this way, but it won't work as expected; an empty result can in fact happen.

> to run 2 queries whenever the package
But I completely agree that this sucks. That's why I asked you for advice on whether or not there is an alternative.

Comment (MihhailSokolov) [reply core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java:1093]: > > a better solution be to prepend the `count(<retrieved field>)`
> 
> I surely thought about this way, but it won't work as expected; an empty result can in fact happen.
> 
> > to run 2 queries whenever the package
> 
> But I completely agree that this sucks. That's why I asked you for advice on whether or not there is an alternative.
> 
> Any thoughts?

Hm, yes, I guess you are right. Then will have to go with 2 queries for now as you implemented. Feel free to merge this when you increase the timeout. Thanks!

Comment (romatallinn) [reply core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java:1093]: > Feel free to merge this when you increase the timeout.

Moved to #277
